from urllib.parse import quote, urlsplit

from trytond.exceptions import UserError
from trytond.i18n import gettext
from trytond.model import ModelSQL, ModelView, Unique, fields
from trytond.pool import PoolMeta
from trytond.pyson import Bool, Eval
from trytond.transaction import Transaction


class PBX(metaclass=PoolMeta):
    __name__ = 'yeastar.pbx'

    webhook_enabled = fields.Boolean('Webhook Enabled')
    webhook_base_url = fields.Char('Public Base URL', states={
            'required': Bool(Eval('webhook_enabled')),
            }, help="Public HTTPS URL of Tryton, including any proxy prefix.")
    webhook_secret = fields.Char('Webhook Secret', strip=True, states={
            'required': Bool(Eval('webhook_enabled')),
            }, help="Copy the signing secret generated by Yeastar.")
    webhook_url = fields.Function(fields.Char('Webhook URL'),
        'get_webhook_url')
    webhook_mode = fields.Selection([
            ('capture', 'Capture Only'),
            ], 'Webhook Mode', required=True, readonly=True)
    webhook_events = fields.One2Many('yeastar.webhook.event', 'pbx',
        'Webhook Events', readonly=True)

    @staticmethod
    def default_webhook_mode():
        return 'capture'

    def get_webhook_url(self, name):
        if self.id is None or self.id < 0 or not self.webhook_base_url:
            return None
        database = quote(Transaction().database.name, safe='')
        return (f'{self.webhook_base_url.rstrip("/")}/{database}'
            f'/yeastar/webhook/{self.id}')

    @classmethod
    def validate(cls, records):
        super().validate(records)
        for record in records:
            if record.webhook_base_url:
                try:
                    url = urlsplit(record.webhook_base_url)
                except ValueError:
                    raise UserError(gettext(
                        'yeastar_api.msg_webhook_invalid_base_url')) from None
                if (url.scheme != 'https' or not url.netloc
                        or url.username or url.password or url.query
                        or url.fragment):
                    raise UserError(gettext(
                        'yeastar_api.msg_webhook_invalid_base_url'))

    @classmethod
    def copy(cls, records, default=None):
        default = default.copy() if default is not None else {}
        default.setdefault('webhook_enabled', False)
        default.setdefault('webhook_secret', None)
        default.setdefault('webhook_events', None)
        return super().copy(records, default=default)


class WebhookEvent(ModelSQL, ModelView):
    'Yeastar Webhook Event'
    __name__ = 'yeastar.webhook.event'
    _rec_name = 'event_type'

    pbx = fields.Many2One('yeastar.pbx', 'PBX', required=True,
        ondelete='RESTRICT', readonly=True)
    event_type = fields.Char('Event Type', required=True, readonly=True)
    call_id = fields.Char('Call ID', readonly=True)
    digest = fields.Char('Payload Digest', required=True, readonly=True)
    payload = fields.Text('Payload', required=True, readonly=True)
    state = fields.Selection([
            ('captured', 'Captured'),
            ], 'State', required=True, readonly=True)

    @classmethod
    def __setup__(cls):
        super().__setup__()
        table = cls.__table__()
        cls._sql_constraints += [
            ('payload_unique', Unique(table, table.pbx, table.digest),
                'yeastar_api.msg_webhook_payload_unique'),
            ]
        cls._order = [('create_date', 'DESC'), ('id', 'DESC')]

    @staticmethod
    def default_state():
        return 'captured'
